openapi: 3.2.0
info:
  title: Ubi Sales Order API
  description: Ubi Api Documenation
  contact:
    email: admin@ubicquia2.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
- url: https://config.api.ubicquia.com/api/
  description: L5 Swagger OpenApi Server
tags:
- name: Sales Order
  description: Operations about Sales Order
paths:
  /update-sales-order:
    put:
      tags:
      - Sales Order
      summary: Update Sales Order by id
      description: ''
      operationId: update
      requestBody:
        $ref: '#/components/requestBodies/SalesOrderRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/salesOrderResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '404':
          $ref: '#/components/responses/404ResourceResponse'
      security:
      - Api Key: []
  /delete-sales-order:
    delete:
      tags:
      - Sales Order
      summary: Deletes Sales order by id
      operationId: destroy
      requestBody:
        $ref: '#/components/requestBodies/SalesOrderDeleteRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/successOperation'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '404':
          $ref: '#/components/responses/404ResourceResponse'
      security:
      - Api Key: []
  /get-sales-order/{sales_order_number}:
    get:
      tags:
      - Sales Order
      summary: get sales order detail
      parameters:
      - $ref: '#/components/parameters/param_sales_order_number'
      responses:
        '200':
          $ref: '#/components/responses/salesOrderResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '404':
          $ref: '#/components/responses/404ResourceResponse'
      security:
      - Api Key: []
      operationId: getGetSalesOrderBySalesOrderNumber
      x-operation-id-source: derived
  /add-sales-order:
    post:
      tags:
      - Sales Order
      summary: Add Sales Order by async
      description: ''
      operationId: add-sales-order
      requestBody:
        $ref: '#/components/requestBodies/AsyncSalesOrderRequestBody'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              example:
                data: Sales Order setup request placed successfully
                status: success
                code: 200
                message: Operation success
                version: value
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '404':
          $ref: '#/components/responses/404ResourceResponse'
      security:
      - Api Key: []
  /get-sales-order-status:
    get:
      tags:
      - Sales Order
      summary: get sales order status
      parameters:
      - name: id
        in: query
        description: Request id
        required: true
        schema:
          type: integer
      - name: customer_id
        in: query
        description: Customer id
        required: true
        schema:
          type: integer
      responses:
        '200':
          $ref: '#/components/responses/salesOrderResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '404':
          $ref: '#/components/responses/404ResourceResponse'
      security:
      - Api Key: []
      operationId: getGetSalesOrderStatus
      x-operation-id-source: derived
  /add-sales-order-config:
    post:
      tags:
      - Sales Order
      summary: Add Sales Order on Config
      description: ''
      operationId: add-sales-order-config
      requestBody:
        $ref: '#/components/requestBodies/SalesOrderRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/salesOrderResponseConfig'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '404':
          $ref: '#/components/responses/404ResourceResponse'
      security:
      - Api Key: []
components:
  parameters:
    param_sales_order_number:
      name: sales_order_number
      in: path
      description: Sales Order Number
      required: true
      schema:
        type: string
  responses:
    salesOrderResponse:
      description: successful operation
      content:
        application/json:
          example:
            data:
              sales_order:
                sales_order_number: string
                customer_id: string
                updated_at: yyyy-mm-dd hh:mm:ss
                created_at: yyyy-mm-dd hh:mm:ss
                id: number
              customer:
                id: number
                customer_id: string
                customer_name: string
                ubivu_address: string
                api_address: string
                mqtt_address: string
                graph_address: string
                parent_customer_id: number
                is_external: boolean
                invoice_to_parent: boolean
                created_at: yyyy-mm-dd hh:mm:ss
                updated_at: yyyy-mm-dd hh:mm:ss
                deleted_at: yyyy-mm-dd hh:mm:ss
                customer_users: number
              parent_customer:
                parent_customer_id: number
                parent_customer_name: string
                updated_at: yyyy-mm-dd hh:mm:ss
                created_at: yyyy-mm-dd hh:mm:ss
                id: number
              users_on_sales_order:
              - id: string
                name: string
                firstname: string
                lastname: string
                email: string
                email_verified_at: timestamp
                license_accepted_id: integer
                terms_accepted_id: integer
                current_customer_id: integer
                last_loggedin: integer
                createdAt: yyyy-mm-dd hh:mm:ss
                updatedAt: yyyy-mm-dd hh:mm:ss
                deactivatedAt: yyyy-mm-dd hh:mm:ss
                isActive: boolean
            status: success
            code: '200'
            message: Operation success
            version: value
    404ResourceResponse:
      description: Item not found
      content:
        application/json:
          example:
            status: failed
            code: 404
            message: Operation failed
    salesOrderResponseConfig:
      description: successful operation
      content:
        application/json:
          example:
            data:
              sales_order_number: string
              customer_id: string
              parent_customer_id: number
              is_international_cust: boolean
              invoice_to_parent: boolean
              updated_at: yyyy-mm-dd hh:mm:ss
              created_at: yyyy-mm-dd hh:mm:ss
              id: number
              country: string
            status: success
            code: '200'
            message: Operation success
            version: value
    successOperation:
      description: successful operation
      content:
        application/json:
          example:
            data:
            - []
            status: success
            message: Operation success
            code: 200
            version: 0.0.0
  requestBodies:
    SalesOrderRequestBody:
      description: Sales Order body param
      required: true
      content:
        application/json:
          schema:
            properties:
              sales_order_number:
                description: Sales Order Number
                type: string
              customer_id:
                description: Customer ID
                type: number
              customer_name:
                description: Customer Name
                type: string
              parent_customer_id:
                description: Parent Customer Id
                type: string
              parent_customer_name:
                description: Parent Customer Name
                type: string
              is_international_cust:
                description: Is international customer
                type: boolean
              invoice_to_parent:
                description: Invoice to parent
                type: boolean
              country:
                description: country iso
                type: string
              users:
                description: Users Details
                type: array
                items:
                  properties:
                    email:
                      type: string
                    firstname:
                      type: string
                    lastname:
                      type: string
                  type: object
            type: object
    SalesOrderDeleteRequestBody:
      description: Sales Order body param
      required: true
      content:
        application/json:
          schema:
            properties:
              sales_order_number:
                description: Sales Order Number
                type: string
              customer_id:
                description: Customer ID
                type: string
            type: object
    AsyncSalesOrderRequestBody:
      description: Sales Order body param
      content:
        application/json:
          schema:
            properties:
              sales_order_number:
                description: Sales Order Number
                type: string
              customer_id:
                description: Customer ID
                type: number
              customer_name:
                description: Customer Name
                type: string
              parent_customer_id:
                description: Parent Customer Id
                type: string
              parent_customer_name:
                description: Parent Customer Name
                type: string
              is_international_cust:
                description: Is international customer
                type: boolean
              invoice_to_parent:
                description: Invoice to parent
                type: boolean
              tenant_step:
                description: tenant creation setps
                type: string
              country:
                description: country iso
                type: string
              skus:
                description: skus
                type: array
                items:
                  type: string
              users:
                description: Users Details
                type: array
                items:
                  properties:
                    email:
                      type: string
                    firstname:
                      type: string
                    lastname:
                      type: string
                  type: object
            type: object
  securitySchemes:
    Api_Key:
      type: apiKey
      description: 'Use header x-api-key: ''key'' to send api key endpoints'
      name: x-api-key
      in: header
