openapi: 3.2.0
info:
  title: Ubi Serial Number API
  description: Ubi Api Documenation
  contact:
    email: admin@ubicquia2.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
servers:
- url: https://config.api.ubicquia.com/api/
  description: L5 Swagger OpenApi Server
tags:
- name: Serial Number
  description: Import serial Number details
paths:
  /update-production-file:
    post:
      tags:
      - Serial Number
      summary: Update Serial Number
      description: 'Allow file: CSV or JSON'
      operationId: update
      requestBody:
        $ref: '#/components/requestBodies/SerialNumberDetailRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/successSerialNumberDetailResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '404':
          $ref: '#/components/responses/404ResourceResponse'
      security:
      - Api Key: []
  /delete-production-file:
    post:
      tags:
      - Serial Number
      summary: Delete Serial Number
      description: ''
      operationId: destroy
      requestBody:
        $ref: '#/components/requestBodies/SerialNumberDetailRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/successSerialNumberDetailResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '404':
          $ref: '#/components/responses/404ResourceResponse'
      security:
      - Api Key: []
  /get-serial-number-list:
    get:
      tags:
      - Serial Number
      summary: Get all serial number details
      description: ''
      operationId: get-serial-number-list
      parameters:
      - name: customer_id
        in: query
        description: Customer Id
        required: false
        schema:
          type: string
          default: ''
      - name: so_number
        in: query
        description: Sales Order Number
        required: false
        schema:
          type: string
          default: ''
      - name: search_type
        in: query
        description: select search type
        required: false
        schema:
          type: string
          default: dev_eui
          enum:
          - serial_number
          - imei
          - dev_eui
          - iccid
          - iccid_secondary
          - fulfillment_id
          - partner_id
          - partner_serial_num
          - partner_item_name
      - name: q
        in: query
        description: searching string
        schema:
          type: string
      - name: page
        in: query
        description: Page number
        schema:
          type: integer
          default: '1'
      - name: per_page
        in: query
        description: Per page items to show in list
        schema:
          type: integer
          default: '20'
      responses:
        '200':
          $ref: '#/components/responses/paginateGetSerialNumberDetailResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '404':
          $ref: '#/components/responses/404ResourceResponse'
      security:
      - Api Key: []
  /check-uploaded-production-file-status:
    get:
      tags:
      - Serial Number
      summary: Get check uploaded production file status
      description: ''
      operationId: check-uploaded-production-file-status
      responses:
        '200':
          $ref: '#/components/responses/checkUploadedProductionFileStatusResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '404':
          $ref: '#/components/responses/404ResourceResponse'
      security:
      - Api Key: []
  /get-production-file-list:
    get:
      tags:
      - Serial Number
      summary: Get all production file details
      description: Get a list of production file details with filtering options.
      operationId: get-production-file-list
      parameters:
      - name: sort_by
        in: query
        description: Sort field (e.g., 'created_at')
        required: false
        schema:
          type: string
          default: created_at
      - name: sort_dir
        in: query
        description: Sort direction ('asc' or 'desc')
        required: false
        schema:
          type: string
          default: desc
      - name: file_type
        in: query
        description: Select file type
        required: false
        schema:
          type: string
          default: prod_file
          enum:
          - prod_file
          - coil_file
      - name: search_type
        in: query
        description: Select search type
        required: false
        schema:
          type: string
          default: filename
          enum:
          - filename
          - name
          - status
      - name: q
        in: query
        description: Searching string
        schema:
          type: string
      - name: page
        in: query
        description: Page number
        schema:
          type: integer
          default: '1'
      - name: per_page
        in: query
        description: Per page items to show in the list
        schema:
          type: integer
          default: '20'
      - name: start_date_time
        in: query
        description: Start Date and Time of the file (yyyy-MM-dd h:m:s)
        schema:
          type: string
      - name: end_date_time
        in: query
        description: End Date and Time of the file (yyyy-MM-dd h:m:s)
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/paginateProductionFileDetailResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthenticated
        '404':
          $ref: '#/components/responses/404ResourceResponse'
      security:
      - Api Key: []
components:
  responses:
    404ResourceResponse:
      description: Item not found
      content:
        application/json:
          example:
            status: failed
            code: 404
            message: Operation failed
    successSerialNumberDetailResponse:
      description: successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SerialNumberDetail'
    paginateProductionFileDetailResponse:
      description: successful operation
      content:
        application/json:
          example:
            data:
            - id: integer
              user_id: string
              action: string
              filename: string
              uploaded_filename: string
              created_at: yyyy-mm-dd hh:mm:ss
              updated_at: yyyy-mm-dd hh:mm:ss
              deleted_at: yyyy-mm-dd hh:mm:ss
              path: string
              user_name: string
            links:
              first: http://hostname/api/get-production-file-list?page=1
              last: http://hostname/api/get-production-file-list?page=1
              prev: number | null
              next: number | null
            meta:
              current_page: 1
              from: 1
              last_page: 1
              path: http://hostname/api/get-production-file-list
              per_page: 20
              to: 2
              total: 2
            status: success
            code: '200'
            message: Operation success
            version: value
    checkUploadedProductionFileStatusResponse:
      description: successful operation
      content:
        application/json:
          example:
            data:
            - count: integer
            status: success
            code: '200'
            message: Operation success
            version: value
    paginateGetSerialNumberDetailResponse:
      description: successful operation
      content:
        application/json:
          example:
            data:
            - customer_id: string
              sales_order_number: string
              serial_number: string
              dev_eui: string
              iccid: string
              sku_part_number: string
              imei: string
              mac_address: string
              imsi: string
              box_id: string
              carton_id: string
              firmware_version: string
              uid: string
              app_key: string
              fulfilled_at: yyyy-mm-dd hh:mm:ss
              production_at: yyyy-mm-dd hh:mm:ss
              updated_at: yyyy-mm-dd hh:mm:ss
              deleted_at: yyyy-mm-dd hh:mm:ss
              triac_test: string
              pwm_test: string
              stpm_test: string
              th_on_test: string
              th_off_test: string
            links:
              first: http://hostname/api/get-serial-number-list?page=1
              last: http://hostname/api/get-serial-number-list?page=1
              prev: number | null
              next: number | null
            meta:
              current_page: 1
              from: 1
              last_page: 1
              path: http://hostname/api/get-serial-number-list
              per_page: 20
              to: 2
              total: 2
            status: success
            code: '200'
            message: Operation success
            version: value
  requestBodies:
    SerialNumberDetailRequestBody:
      content:
        multipart/form-data:
          schema:
            properties:
              csvFile:
                type: file
            type: object
  schemas:
    SerialNumberDetail:
      properties:
        csvFile:
          type: file
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
      type: object
  securitySchemes:
    Api_Key:
      type: apiKey
      description: 'Use header x-api-key: ''key'' to send api key endpoints'
      name: x-api-key
      in: header
